/** Restriction-floor DATA. Topics never grant permission; rules deliberately
 * over-recognize restrictions and leave every other topical unit unclear. */
export type PolicyDimension = 'ai' | 'assignment' | 'directPr' | 'draft' | 'template' | 'baseline';
export type PolicyCategory =
  | 'ai_ban'
  | 'ai_approval'
  | 'ai_disclosure'
  | 'assignment_required'
  | 'discussion_first'
  | 'draft_required'
  | 'template_fixed'
  | 'baseline_forbidden';
export interface PolicyRule {
  readonly id: string;
  readonly category: PolicyCategory;
  readonly pattern: string;
}
export interface PolicyTopic {
  readonly dimension: PolicyDimension;
  readonly id: string;
  readonly pattern: string;
}

export const POLICY_AI_MENTION =
  '\\b(?:ai|a[.]i[.]|llms?|large language models?|artificial intelligence|gen[- ]?ai|generative ai|gpt(?:[- ]?\\d+)?|chat[- ]?gpt|claude|gemini|cursor|codex|copilot|generated by|machine[- ]generated|assistant)\\b';
export const POLICY_NEGATION =
  '\\b(?:not|no|never|cannot|prohibited|banned|forbidden|disallowed|reject(?:ed|s|ing)?|must not)\\b';
// Retained as an inert compatibility alias; there are no permission rules.
export const POLICY_PERMISSION_CAVEAT = POLICY_NEGATION;
export const POLICY_TOPICS: readonly PolicyTopic[] = Object.freeze(
  [
    { dimension: 'ai', id: 'topic-ai', pattern: POLICY_AI_MENTION },
    {
      dimension: 'assignment',
      id: 'topic-assignment',
      pattern: '\\b(?:assign(?:ment|ed|ing)?|assignees?)\\b',
    },
    {
      dimension: 'directPr',
      id: 'topic-direct-pr',
      pattern: '\\b(?:prs?|pull[- ]requests?|discuss(?:ion|ing)?|discussion)\\b',
    },
    { dimension: 'draft', id: 'topic-draft', pattern: '\\bdrafts?\\b' },
    {
      dimension: 'template',
      id: 'topic-template',
      pattern: '\\b(?:templates?|(?:extra|additional) sections|receipt blocks?)\\b',
    },
    {
      dimension: 'baseline',
      id: 'topic-baseline',
      pattern: '\\b(?:baseline|pre[- ]existing|unrelated (?:test )?failures?)\\b',
    },
  ].map((topic) => Object.freeze(topic as PolicyTopic))
);

const REQUIRED = '\\b(?:requires?|required|must|needs?|mandatory|before|first)\\b';
const GAP = '[^.!?;\\n]{0,256}';
export const POLICY_RULES: readonly PolicyRule[] = Object.freeze(
  [
    { id: 'ai-ban-1', category: 'ai_ban', pattern: POLICY_NEGATION },
    {
      id: 'ai-approval-1',
      category: 'ai_approval',
      pattern: `\\b(?:approval|permission|consent)\\b${GAP}${REQUIRED}|${REQUIRED}${GAP}\\b(?:approval|permission|consent)\\b`,
    },
    {
      id: 'ai-disclosure-1',
      category: 'ai_disclosure',
      pattern: `\\b(?:disclos(?:e|ed|ure)|declar(?:e|ation))\\b${GAP}${REQUIRED}|${REQUIRED}${GAP}\\b(?:disclos(?:e|ed|ure)|declar(?:e|ation))\\b`,
    },
    { id: 'assignment-required-1', category: 'assignment_required', pattern: REQUIRED },
    {
      id: 'discussion-first-1',
      category: 'discussion_first',
      pattern: `\\b(?:discuss(?:ion)?|contact|open an issue)\\b${GAP}\\b(?:first|before|prior)\\b|\\b(?:first|before)\\b${GAP}\\bdiscuss(?:ion)?\\b|${REQUIRED}${GAP}\\b(?:approval|permission|consent)\\b`,
    },
    { id: 'draft-required-1', category: 'draft_required', pattern: REQUIRED },
    {
      id: 'template-fixed-1',
      category: 'template_fixed',
      pattern: '\\b(?:unchanged|unmodified|fixed|keep|leave)\\b',
    },
    { id: 'baseline-forbidden-1', category: 'baseline_forbidden', pattern: POLICY_NEGATION },
    { id: 'negation-assignment', category: 'assignment_required', pattern: POLICY_NEGATION },
    { id: 'negation-directPr', category: 'discussion_first', pattern: POLICY_NEGATION },
    { id: 'negation-draft', category: 'draft_required', pattern: POLICY_NEGATION },
    { id: 'negation-template', category: 'template_fixed', pattern: POLICY_NEGATION },
  ].map((rule) => Object.freeze(rule as PolicyRule))
);
