#!/usr/bin/env bash
# Weekly cron: regenerate docs/reports/model-scorecard.md + the JSON sidecar (#566),
# open/refresh a PR with the new snapshot, and post the 6-line digest to Telegram.
#
# Reference install, like the rest of scripts/sched-fleet/ — copy and edit per
# deployment (see scripts/sched-fleet/README.md). Cron line (weekly):
#   0 5 * * 1  /path/to/scorecard-weekly.sh >> /path/to/scorecard-weekly.log 2>&1
#
# Runs in a DEDICATED worktree, never the main checkout — this repo's AGENTS.md
# forbids checking out branches in the main worktree (it breaks parallel agents
# already running there), so a fixed worktree at worktrees/chore-model-scorecard-weekly
# is created once and reused/rewritten every run, exactly like
# refresh-examples-snapshot.mjs's PR branch: any manual commit pushed to
# chore/model-scorecard-weekly between runs is discarded by the next one.
#
# This repo has no auto-merge watcher (see AGENTS.md), so this script only opens or
# updates the PR — it never merges. A human or an agent run merges it.
set -u
export PATH="$HOME/.local/bin:$HOME/.nvm/versions/node/v24.20.0/bin:/usr/local/bin:/usr/bin:/bin"
D="${SCHED_FLEET_HOME:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}"
source "$D/telegram.env"
TG() { curl -s --max-time 20 "https://api.telegram.org/bot${HANEST_TELEGRAM_BOT_TOKEN}/sendMessage" \
        -d chat_id="${HANEST_TELEGRAM_CHAT_ID}" --data-urlencode text="$1" >/dev/null 2>&1; }

REPO="${SCORECARD_REPO:-$HOME/projects/ai-dossier/main}"
WT="$REPO/worktrees/chore-model-scorecard-weekly"
BRANCH="chore/model-scorecard-weekly"
LOG="$D/scorecard-weekly.log"
DIGEST_FILE="$D/scorecard-weekly-digest.txt"

log() { echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] $*" >>"$LOG"; }

cd "$REPO" || { TG "❌ model-scorecard weekly: repo not found at $REPO"; exit 1; }
if ! git fetch origin main >>"$LOG" 2>&1; then
  TG "❌ model-scorecard weekly run failed on hcc2 (git fetch) — see $LOG"
  exit 1
fi

if [ -d "$WT" ]; then
  git -C "$WT" fetch origin main >>"$LOG" 2>&1
  git -C "$WT" checkout -B "$BRANCH" origin/main >>"$LOG" 2>&1
else
  git branch -f "$BRANCH" origin/main >>"$LOG" 2>&1
  git worktree add "$WT" "$BRANCH" >>"$LOG" 2>&1
fi
if [ ! -d "$WT" ]; then
  TG "❌ model-scorecard weekly run failed on hcc2 (worktree setup) — see $LOG"
  exit 1
fi

cd "$WT" || { TG "❌ model-scorecard weekly: cannot cd into $WT"; exit 1; }
if ! npm install --no-audit --no-fund >>"$LOG" 2>&1; then
  TG "❌ model-scorecard weekly run failed on hcc2 (npm install) — see $LOG"
  exit 1
fi
if ! make build-all >>"$LOG" 2>&1; then
  TG "❌ model-scorecard weekly run failed on hcc2 (build) — see $LOG"
  exit 1
fi

# A dedicated digest file, not a log grep — the digest can't be confused with
# npm install/build output landing in the same log, and doesn't depend on the
# script's own log-message wording matching a grep pattern.
rm -f "$DIGEST_FILE"
if ! npm run scorecard -- --digest-out "$DIGEST_FILE" >>"$LOG" 2>&1; then
  TG "❌ model-scorecard weekly run failed on hcc2 (scorecard) — see $LOG"
  exit 1
fi
if [ ! -f "$DIGEST_FILE" ]; then
  TG "❌ model-scorecard weekly run on hcc2 exited 0 but wrote no digest — see $LOG"
  exit 1
fi
DIGEST=$(cat "$DIGEST_FILE")

if git diff --quiet -- docs/reports/model-scorecard.md docs/reports/evidence/model-scorecard.json; then
  TG "$DIGEST
(no changes this week)"
  exit 0
fi

if ! git add docs/reports/model-scorecard.md docs/reports/evidence/model-scorecard.json \
  || ! git commit -m "chore(reports): weekly model scorecard refresh" >>"$LOG" 2>&1 \
  || ! git push -f -u origin "$BRANCH" >>"$LOG" 2>&1; then
  TG "❌ model-scorecard weekly: commit/push failed on hcc2 — see $LOG (digest was: $DIGEST)"
  exit 1
fi

if gh pr view "$BRANCH" --json number >>"$LOG" 2>&1; then
  gh pr edit "$BRANCH" --body "Automated weekly refresh of the model scorecard — see #566." >>"$LOG" 2>&1
else
  gh pr create --base main --head "$BRANCH" \
    --title "chore(reports): weekly model scorecard refresh" \
    --body "Automated weekly refresh of the model scorecard (#566), regenerated by \`scorecard-weekly.sh\` on hcc2. This repo has no auto-merge watcher — review and merge manually." >>"$LOG" 2>&1
fi
if ! gh pr view "$BRANCH" --json number >>"$LOG" 2>&1; then
  TG "$DIGEST
⚠️ PR open/update did not confirm — check $LOG"
  exit 1
fi

TG "$DIGEST"
