#!/usr/bin/env bash
# Weekly cron: regenerate docs/reports/model-scorecard.md + the JSON sidecar (#566),
# open/refresh a PR with the new snapshot, and post the 6-line digest to Telegram.
#
# Reference install, like the rest of scripts/sched-fleet/ — copy and edit per
# deployment (see scripts/sched-fleet/README.md). Cron line (weekly):
#   0 5 * * 1  /path/to/scorecard-weekly.sh >> /path/to/scorecard-weekly.log 2>&1
#
# Runs in a DEDICATED worktree, never the main checkout — this repo's AGENTS.md
# forbids checking out branches in the main worktree (it breaks parallel agents
# already running there), so a fixed worktree at worktrees/chore-model-scorecard-weekly
# is created once and reused/rewritten every run, exactly like
# refresh-examples-snapshot.mjs's PR branch: any manual commit pushed to
# chore/model-scorecard-weekly between runs is discarded by the next one.
#
# This repo has no auto-merge watcher (see AGENTS.md), so this script only opens or
# updates the PR — it never merges. A human or an agent run merges it.
set -u
export PATH="$HOME/.local/bin:$HOME/.nvm/versions/node/v24.20.0/bin:/usr/local/bin:/usr/bin:/bin"
D="${SCHED_FLEET_HOME:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}"
source "$D/telegram.env"

REPO="${SCORECARD_REPO:-$HOME/projects/ai-dossier/main}"
WT="$REPO/worktrees/chore-model-scorecard-weekly"
BRANCH="chore/model-scorecard-weekly"

cd "$REPO" || exit 1
git fetch origin main >/dev/null 2>&1

if [ -d "$WT" ]; then
  git -C "$WT" fetch origin main >/dev/null 2>&1
  git -C "$WT" checkout -B "$BRANCH" origin/main >/dev/null 2>&1
else
  git branch -f "$BRANCH" origin/main >/dev/null 2>&1
  git worktree add "$WT" "$BRANCH" >/dev/null 2>&1
fi

cd "$WT" || exit 1
npm install --no-audit --no-fund >/dev/null 2>&1
make build-all >/dev/null 2>&1

LOG="$D/scorecard-weekly.log"
npm run scorecard >"$LOG" 2>&1
STATUS=$?
DIGEST=$(grep -A6 "Model scorecard" "$LOG")

if [ "$STATUS" -ne 0 ]; then
  TG "❌ model-scorecard weekly run failed on hcc2 — see $LOG"
  exit 1
fi

if git diff --quiet -- docs/reports/model-scorecard.md docs/reports/evidence/model-scorecard.json; then
  TG "$DIGEST
(no changes this week)"
  exit 0
fi

git add docs/reports/model-scorecard.md docs/reports/evidence/model-scorecard.json
git commit -m "chore(reports): weekly model scorecard refresh" >/dev/null 2>&1
git push -f -u origin "$BRANCH" >/dev/null 2>&1

if gh pr view "$BRANCH" --json number >/dev/null 2>&1; then
  gh pr edit "$BRANCH" --body "Automated weekly refresh of the model scorecard — see #566." >/dev/null 2>&1
else
  gh pr create --base main --head "$BRANCH" \
    --title "chore(reports): weekly model scorecard refresh" \
    --body "Automated weekly refresh of the model scorecard (#566), regenerated by \`scorecard-weekly.sh\` on hcc2. This repo has no auto-merge watcher — review and merge manually." >/dev/null 2>&1
fi

TG "$DIGEST"
