export {
  type AmbiguousTest,
  attributeByOverlap,
  type BoundaryCommit,
  type FailingTest,
  failingTest,
  type MemberFootprint,
  type MemberRange,
  memberOfCommit,
  memberRanges,
  type OverlapAttribution,
  offendersOf,
  parseBoundaryCommits,
  parseVitestJson,
  SAFE_REF_RE,
  SHA_RE,
} from './attribution';
export {
  type BatchDispatchDeps,
  type BatchTickResult,
  type CapOutcome,
  runBatchTick,
} from './batch-dispatch';
export { type BisectOptions, type BisectOutcome, runAttributionBisect } from './bisect';
export {
  buildAgentCommand,
  buildBatchReportPrompt,
  buildBatchTailPrompt,
  buildFixPrompt,
  buildMemberPrompt,
  buildPrompt,
  buildReportPrompt,
  createSpawnDeps,
  DEFAULT_BATCH_REPORT_PROMPT_TEMPLATE,
  DEFAULT_BATCH_TAIL_PROMPT_TEMPLATE,
  DEFAULT_DISPATCH_COMMAND,
  DEFAULT_FIX_PROMPT_TEMPLATE,
  DEFAULT_MEMBER_PROMPT_TEMPLATE,
  DEFAULT_PROMPT_TEMPLATE,
  DEFAULT_REPORT_PROMPT_TEMPLATE,
  DEFAULT_TIER_MODELS,
  dispatchLogPath,
  escalateTier,
  fileSizeOrZero,
  NO_BACKGROUND_EXIT_INSTRUCTION,
  OPENCODE_DISPATCH_COMMAND,
  type ResolvedDispatch,
  reportTierFor,
  resolveDispatch,
  type SpawnDeps,
  SUPERSESSION_CHECKPOINT_INSTRUCTION,
  stallTimeoutForPhase,
  stallTimeoutForSlot,
  takeoverInstruction,
  unitLogName,
} from './dispatch';
export { type EngineDeps, runLoop, type TickResult, tick } from './engine';
export {
  assertNoDependencyCycle,
  EnqueueError,
  type EnqueueInput,
  enqueueEntries,
  LABEL_BLOCK_REASON_PREFIX,
  labelBlockReason,
  parseManifest,
} from './enqueue';
export {
  createExecRunFencer,
  FENCE_TIMEOUT_MS,
  type FenceOutcome,
  parseFenceGeneration,
  type RunFencer,
} from './fence';
export {
  createExecGroundTruth,
  type GroundTruth,
  type GroundTruthMilestone,
  groundTruthExec,
  isBatchPhaseDone,
  isBatchTailParked,
  isMemberBlocked,
  isMemberComplete,
  isParkedMilestone,
  isVerifiedComplete,
  labelNames,
  type PrTruth,
  parseMilestoneJson,
  parsePrViewJson,
  parseSetupInfo,
  prOfMilestone,
  type SetupInfo,
} from './groundtruth';
export {
  appendJsonl,
  batchOfUnit,
  issueOfUnit,
  JOURNAL_FILE,
  Journal,
  readJsonl,
  unitEvent,
} from './journal';

export { CorruptStateError, LockTimeoutError, SchedStore, writeAtomic } from './persist';
export {
  createExecFn,
  defaultExec,
  type ExecFn,
  resolveProjectSlug,
  sanitizeSlug,
  schedStateDir,
} from './project';
export { DISPATCHABLE_ISSUE_STATUSES } from './readiness';
export {
  type AttributionInput,
  type AttributionOutcome,
  type BatchMilestone,
  type BatchMilestonePoster,
  type BisectSpec,
  beginAttribution,
  beginFixAttempt,
  checkDissolveTrigger,
  createExecMilestonePoster,
  type DissolveOptions,
  type DissolveOutcome,
  dissolveBatch,
  type EvictionInput,
  type EvictionOutcome,
  evictMembers,
  expandEvictionGroups,
  type FixDispatch,
  handlePrConflict,
  type JournalLike,
  type PrConflictAction,
  type PrConflictOutcome,
  type RecoveryDeps,
  resolveFixAttempt,
  type SuiteResult,
  type SuiteRunner,
} from './recovery';
export {
  appendSchedRunLog,
  buildSchedRunLogEntry,
  readDispatchLog,
  type SchedRunLogInput,
  schedRunsLogPath,
  schedTelemetryEnabled,
  usageParserFor,
} from './run-log';
export {
  type Assignment,
  abandonBatch,
  abandonIssue,
  assignToIdleSlot,
  batchBlockers,
  computeAssignments,
  type DependencyBlocker,
  dependencyBlockers,
  freeCapacity,
  type RunnableUnit,
  runnableUnits,
  setPaused,
} from './scheduler';
export {
  createBatch,
  createEmptyState,
  findBatch,
  findEntry,
  isPreservedMember,
  patchBatch,
  requeueMember,
  TRANSITIONS,
  transitionBatch,
  transitionIssue,
  transitionSlot,
  validateState,
} from './state';
export { type BlockedItem, buildStatusReport, type ParkedItem, type StatusReport } from './status';
export { isSafeWorktree, runTeardown, TEARDOWN_TIMEOUT_MS, type TeardownResult } from './teardown';
export {
  type AttributionMethod,
  BATCH_PHASES,
  type BatchEntry,
  type BatchPhase,
  type BatchStatus,
  type CleanupStatus,
  CONFIG_SCHEMA_VERSION,
  type CycleMode,
  DEFAULT_MAX_SLOTS,
  DEFAULT_PHASE_STALL_TIMEOUT_MS,
  DEFAULT_PR_POLL_INTERVAL_MS,
  DEFAULT_RECONCILE_INTERVAL_MS,
  DEFAULT_STALL_TIMEOUT_MS,
  DISSOLVE_EVICTION_FRACTION,
  type DispatchConfig,
  ESCALATION_CAP,
  type EvictionRecord,
  type FailureEvidence,
  FIX_ATTEMPT_TIER,
  type FixAttemptRecord,
  IllegalTransitionError,
  type IssueStatus,
  type JournalEvent,
  type JournalEventName,
  LEGACY_CONFIG_SCHEMA_VERSIONS,
  LEGACY_SCHEMA_VERSIONS,
  LIVE_SLOT_STATUSES,
  MAX_FIX_ATTEMPTS_PER_MEMBER,
  MAX_MAX_SLOTS,
  MAX_REBASE_ATTEMPTS,
  MERGED_BATCH_STATUSES,
  MIN_MAX_SLOTS,
  type ModelTier,
  PHASES,
  type Phase,
  type QueueEntry,
  SATISFIED_ISSUE_STATUSES,
  SCHEMA_VERSION,
  type SchedConfig,
  type SchedConfigFile,
  SchedNotFoundError,
  type SchedState,
  SLOT_ROLES,
  type SlotEntry,
  type SlotRole,
  type SlotStatus,
  TERMINAL_BATCH_STATUSES,
  TERMINAL_ISSUE_STATUSES,
  TIER_LADDER,
  TIER_ORDER,
} from './types';
