export {
  ANCHOR_CLOSE_BATCH_STATUSES,
  type AnchorCloseOutcome,
  type AnchorMemberReport,
  type AnchorReportItem,
  type AnchorVerdict,
  anchorCloseMarker,
  anchorLedgerBlockers,
  batchAnchorStillOpen,
  type CommitInBase,
  classifyAnchor,
  classifyOrphanAnchor,
  closeAnchor,
  DEFAULT_ORPHAN_BASE_BRANCH,
  formatBatchStatus,
  type IssueCloseReader,
  type MembersVerdictOptions,
  membersShippedVerdict,
  type OpenAnchorIssue,
  type OpenAnchorLister,
  type OpenAnchorVerdict,
  ORPHAN_SWEEP_MAX_ANCHORS,
  ORPHAN_SWEEP_MAX_MEMBERS,
  type OrphanAnchorCandidate,
  type OrphanAnchorReportItem,
  type OrphanAnchorSweepResult,
  type OrphanAnchorVerdict,
  openAnchorBatches,
  orphanAnchorListArgs,
  parseOrphanAnchorBody,
  renderAnchorCloseComment,
  shippingEvidence,
  sweepAnchors,
  sweepOrphanAnchors,
} from './anchor-close';
export {
  type AmbiguousTest,
  attributeByOverlap,
  type BoundaryCommit,
  type FailingTest,
  failingTest,
  hasEarnedFailureEvidence,
  hasFailingTestEvidence,
  isReadableVitestReport,
  type MemberFootprint,
  type MemberRange,
  memberOfCommit,
  memberRanges,
  type OverlapAttribution,
  offendersOf,
  parseBoundaryCommits,
  parseVitestJson,
  SAFE_REF_RE,
  SHA_RE,
} from './attribution';
export {
  type BatchDispatchDeps,
  type BatchTickResult,
  type CapOutcome,
  memberBranchFor,
  resumeBlockedGate,
  runBatchTick,
} from './batch-dispatch';
export {
  type BatchLogEntry,
  buildBatchRunLogEntries,
  dispatchPreambleCmd,
  listBatchDispatchLogs,
  modelFromCmd,
  parsePreambleLine,
} from './batch-stats';
export { type BisectOptions, type BisectOutcome, runAttributionBisect } from './bisect';
export {
  buildAgentCommand,
  buildBatchReportPrompt,
  buildBatchTailPrompt,
  buildCommandForModel,
  buildFixPrompt,
  buildMemberPrompt,
  buildPrompt,
  buildReportPrompt,
  buildTierCommand,
  createSpawnDeps,
  DEFAULT_BATCH_REPORT_PROMPT_TEMPLATE,
  DEFAULT_BATCH_TAIL_PROMPT_TEMPLATE,
  DEFAULT_DISALLOWED_TOOLS,
  DEFAULT_DISPATCH_COMMAND,
  DEFAULT_FIX_PROMPT_TEMPLATE,
  DEFAULT_MEMBER_PROMPT_TEMPLATE,
  DEFAULT_PROMPT_TEMPLATE,
  DEFAULT_REPORT_PROMPT_TEMPLATE,
  DEFAULT_TIER_MODELS,
  DISPATCH_PROFILE_RE,
  DispatchProfileError,
  dispatchLogPath,
  dispatchSummary,
  escalateTier,
  FULL_REVIEW_MEMBER_DIRECTIVE,
  fileSizeOrZero,
  HEADLESS_BACKGROUND_GUARD_HOOK_COMMAND,
  HEADLESS_BACKGROUND_GUARD_SETTINGS,
  journalCmdModelFields,
  memberDispatchTier,
  NO_BACKGROUND_EXIT_INSTRUCTION,
  OPENCODE_DISPATCH_COMMAND,
  priorWorkInstruction,
  procStartTime,
  type ResolvedDispatch,
  type ResolvedTierDispatch,
  reportTierFor,
  resolveDispatch,
  resolveProfiledDispatch,
  resolveTierSpawn,
  type SpawnDeps,
  SUPERSESSION_CHECKPOINT_INSTRUCTION,
  stallTimeoutForPhase,
  stallTimeoutForSlot,
  type TierExecutor,
  type TierSpawn,
  takeoverInstruction,
  tierExecutors,
  unitLogName,
} from './dispatch';
export { type EngineDeps, recordTickFailure, runLoop, type TickResult, tick } from './engine';
export {
  assertNoDependencyCycle,
  EnqueueError,
  type EnqueueInput,
  type EnqueueOptions,
  enqueueEntries,
  LABEL_BLOCK_REASON_PREFIX,
  labelBlockReason,
  parseManifest,
} from './enqueue';
export {
  createExecRunFenceBinder,
  createExecRunFenceReleaser,
  createExecRunFencer,
  FENCE_TIMEOUT_MS,
  type FenceOutcome,
  parseFenceGeneration,
  type RunFenceBinder,
  type RunFenceReleaser,
  type RunFencer,
  takeoverLabelFor,
} from './fence';
export {
  createExecGroundTruth,
  GIT_OID_RE,
  type GroundTruth,
  type GroundTruthMilestone,
  groundTruthExec,
  type IssueCloseTruth,
  isBatchPhaseDone,
  isBatchTailParked,
  isMemberBlocked,
  isMemberComplete,
  isParkedMilestone,
  issueCloseReader,
  isVerifiedComplete,
  labelNames,
  memberBlockedReason,
  type PrTruth,
  parseIssueCloseTruthJson,
  parseIssueLabelsJson,
  parseMilestoneJson,
  parseMilestoneListJson,
  parseOpenPrListJson,
  parsePrViewJson,
  parseRepoName,
  parseSetupInfo,
  prOfMilestone,
  REVIEW_PARTIAL_REASON,
  type SetupInfo,
} from './groundtruth';
export {
  appendJsonl,
  batchOfUnit,
  issueOfUnit,
  JOURNAL_FILE,
  Journal,
  readJsonl,
  unitEvent,
} from './journal';
// `LABEL_BLOCK_REASON_PREFIX` / `labelBlockReason` also live in `labels.ts`
// since #544, but stay exported through `./enqueue` above — that is where
// they were first public, and re-exporting them twice would collide.
export {
  BATCH_ANCHOR_LABEL,
  DECISION_PENDING_LABEL,
  HARD_BLOCK_LABELS,
  hasLabel,
  labelOfBlockReason,
  pickHardBlockLabel,
} from './labels';
export {
  CorruptStateError,
  type EngineLease,
  type EngineLeaseAcquisition,
  type EngineLeaseHolder,
  type EngineLeaseStatus,
  LockTimeoutError,
  SchedStore,
  writeAtomic,
} from './persist';
export {
  createExecFn,
  defaultExec,
  type ExecFn,
  resolveProjectRepo,
  resolveProjectSlug,
  sanitizeSlug,
  schedStateDir,
} from './project';
export {
  batchRank,
  compareByPriority,
  DISPATCHABLE_ISSUE_STATUSES,
  entryRank,
  type PriorityRank,
} from './readiness';
export {
  type AttributionInput,
  type AttributionOutcome,
  type BatchMilestone,
  type BatchMilestonePoster,
  type BatchSuiteContext,
  type BisectSpec,
  type BlockOptions,
  beginAttribution,
  beginFixAttempt,
  blockBatch,
  checkDissolveTrigger,
  createExecMilestonePoster,
  DISSOLVE_REFUSED_PREFIX,
  type DissolveOptions,
  type DissolveOutcome,
  dissolveBatch,
  type EvictionInput,
  type EvictionOutcome,
  evictMembers,
  expandEvictionGroups,
  type FixDispatch,
  handlePrConflict,
  type JournalLike,
  type PrConflictAction,
  type PrConflictOutcome,
  type RecoveryDeps,
  resolveFixAttempt,
  type SuiteResult,
  type SuiteRunner,
} from './recovery';
export {
  appendSchedRunLog,
  buildSchedRunLogEntry,
  type FenceAbortEvidence,
  finalizeRunLogEntry,
  parseFenceAbort,
  readDispatchLog,
  type SchedRunLogInput,
  schedRunsLogPath,
  schedTelemetryEnabled,
  usageParserFor,
} from './run-log';
export {
  type Assignment,
  abandonBatch,
  abandonIssue,
  assignToIdleSlot,
  batchBlockers,
  computeAssignments,
  type DependencyBlocker,
  dependencyBlockers,
  freeCapacity,
  type RunnableUnit,
  reprioritizeBatch,
  reprioritizeIssue,
  requeueParkedMember,
  runnableUnits,
  setPaused,
  stopBatch,
  stopIssue,
} from './scheduler';
export {
  allowedBatchTransitions,
  appendEvictions,
  batchMemberUnit,
  createBatch,
  createEmptyState,
  distinctEvictions,
  duplicateEvictionDetail,
  findBatch,
  findEntry,
  isPreservedMember,
  type MemberExitExtra,
  memberDispatchProfile,
  memberExitEvidence,
  PARKED_MEMBER_STATUSES,
  parkMember,
  patchBatch,
  patchSlot,
  recordedMemberBranch,
  requeueMember,
  slotsForBatch,
  TRANSITIONS,
  transitionBatch,
  transitionIssue,
  transitionSlot,
  validatedMembersOf,
  validateState,
} from './state';
export {
  type BlockedItem,
  buildKeptWorktreeWarnings,
  buildStatusReport,
  buildStatusWarnings,
  defaultKeptWorktreeReader,
  KEPT_WORKTREE_PROBE_LIMIT,
  type KeptWorktreeCandidate,
  type KeptWorktreeReader,
  keptWorktreeCandidates,
  type ParkedItem,
  type ParkedMemberItem,
  STATUS_HEALTH_WARNING_AGE_MS,
  type StatusReport,
  type StatusWarning,
  type StatusWarningKind,
} from './status';
export {
  defaultFsExists,
  type FsExists,
  isSafeWorktree,
  POOL_ARGS_PREFIX,
  POOL_BIN,
  poolEntryFor,
  runTeardown,
  TEARDOWN_TIMEOUT_MS,
  type TeardownResult,
} from './teardown';
export {
  type AttributionMethod,
  BATCH_PHASES,
  type BatchEntry,
  type BatchPhase,
  type BatchStatus,
  type CapabilityGateResult,
  type CleanupStatus,
  CONFIG_SCHEMA_VERSION,
  type CycleMode,
  DEFAULT_BATCH_PRIORITY,
  DEFAULT_DISSOLVE_POLICY,
  DEFAULT_ISSUE_PRIORITY,
  DEFAULT_LABEL_POLL_INTERVAL_MS,
  DEFAULT_MAX_SLOTS,
  DEFAULT_PHASE_STALL_TIMEOUT_MS,
  DEFAULT_PR_POLL_INTERVAL_MS,
  DEFAULT_RECONCILE_INTERVAL_MS,
  DEFAULT_STALL_TIMEOUT_MS,
  DISSOLVE_EVICTION_FRACTION,
  type DispatchConfig,
  type DispatchProfile,
  type DissolvePolicy,
  EngineTooOldError,
  ESCALATION_CAP,
  type EvictionRecord,
  type FailureEvidence,
  FIX_ATTEMPT_TIER,
  type FixAttemptRecord,
  IllegalTransitionError,
  type IssueStatus,
  JOURNAL_DEDUP_REANNOUNCE_TICKS,
  type JournalEvent,
  type JournalEventName,
  LEGACY_CONFIG_SCHEMA_VERSIONS,
  LEGACY_SCHEMA_VERSIONS,
  LIVE_SLOT_STATUSES,
  MAX_FIX_ATTEMPTS_PER_MEMBER,
  MAX_FULL_REVIEW_MEMBERS,
  MAX_MAX_SLOTS,
  MAX_REBASE_ATTEMPTS,
  MEMBER_EXIT_KINDS,
  MEMBER_RUN_STATUSES,
  MERGED_BATCH_STATUSES,
  type MemberDispatchMode,
  type MemberExitKind,
  type MemberRun,
  type MemberRunStatus,
  MIN_MAX_SLOTS,
  type ModelTier,
  PHASES,
  type Phase,
  type QueueEntry,
  type ReviewLevel,
  SATISFIED_ISSUE_STATUSES,
  SCHEMA_VERSION,
  type SchedConfig,
  type SchedConfigFile,
  SchedNotFoundError,
  type SchedState,
  SLOT_ROLES,
  type SlotEntry,
  type SlotReleaseReason,
  type SlotRole,
  type SlotStatus,
  TERMINAL_BATCH_STATUSES,
  TERMINAL_ISSUE_STATUSES,
  TIER_LADDER,
  TIER_ORDER,
  type TierDispatchSpec,
} from './types';
