import { createHash } from 'node:crypto';
import { readdirSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import { canonicalJson, ReceiptError } from '../../receipt/schema';
import { assertNoSecrets } from '../../redaction';
import { classifyPolicy, policyDigest } from '../classify';
import { type PolicyFile, PolicyInputError } from '../discover';
import { POLICY_RULES, POLICY_TOPICS } from '../rules';

function policyFile(content: string, path = 'CONTRIBUTING.md'): PolicyFile {
  const bytes = Buffer.from(content);
  const sha = createHash('sha1').update(`blob ${bytes.length}\0`).update(bytes).digest('hex');
  return { path, sha, content };
}
const fixtureRoot = resolve(__dirname, '../../../fixtures/policy');
const fixtures = readdirSync(fixtureRoot)
  .filter((path) => path.endsWith('.json'))
  .sort()
  .map((name) => ({
    name,
    ...(JSON.parse(readFileSync(resolve(fixtureRoot, name), 'utf8')) as {
      files: Record<string, string>;
      expected: object;
      actor: string;
      slice: string;
      expectedOutcome: string;
    }),
  }));

describe('restriction-floor fixtures', () => {
  it('has at least 15 synthetic fixtures and frozen identifiable rule data', () => {
    expect(fixtures.length).toBeGreaterThanOrEqual(15);
    const ids = [...POLICY_RULES, ...POLICY_TOPICS].map((rule) => rule.id);
    expect(new Set(ids).size).toBe(ids.length);
    expect(Object.isFrozen(POLICY_RULES)).toBe(true);
    expect(Object.isFrozen(POLICY_TOPICS)).toBe(true);
    expect([...POLICY_RULES, ...POLICY_TOPICS].every(Object.isFrozen)).toBe(true);
  });
  it.each(fixtures)('$name', ({ files, expected, actor, slice, expectedOutcome }) => {
    expect(['hostile_repository', 'upstream_maintainer']).toContain(actor);
    expect(slice).toBe('S2');
    expect(expectedOutcome.length).toBeGreaterThan(0);
    const input = Object.entries(files).map(([path, content]) => policyFile(content, path));
    const { citations, ...assessment } = classifyPolicy(input);
    expect(assessment).toEqual(expected);
    expect(assessment.ai).not.toBe('welcomed');
    expect(assessment.directPr).not.toBe('welcomed');
    expect(assessment.baselineFailuresPermitted).toBe(false);
    for (const citation of citations) {
      const file = input.find((value) => value.path === citation.path);
      expect(citation.excerpt).toBe(file?.content.split(/\r\n|\n|\r/u)[citation.line - 1]);
      expect(
        [...POLICY_RULES, ...POLICY_TOPICS].some((rule) => rule.id === citation.ruleId) ||
          citation.ruleId.startsWith('markdown-ambiguous-')
      ).toBe(true);
      expect(() => assertNoSecrets(citation.excerpt)).not.toThrow();
    }
  });
});

describe('broad topics and restriction precedence', () => {
  it.each([
    'AI',
    'A.I.',
    'LLM',
    'large language model',
    'ChatGPT',
    'Copilot',
    'generated by',
    'machine-generated',
    'assistant',
  ])('detects AI topic %s without inferring permission', (topic) => {
    expect(classifyPolicy([policyFile(`${topic} is welcome.`)]).ai).toBe('unclear');
    expect(classifyPolicy([policyFile(`No ${topic} contributions.`)]).ai).toBe('banned');
  });
  it.each([
    "isn't",
    'isn’t',
    "aren't",
    "won't",
    "can't",
    'must not',
    'never',
    'prohibited',
    'forbidden',
    'disallowed',
    'reject',
  ])('normalizes or recognizes restrictive %s', (word) => {
    expect(classifyPolicy([policyFile(`AI ${word} allowed.`)]).ai).toBe('banned');
  });
  it('uses the strictest restriction instead of treating cumulative restrictions as conflict', () => {
    expect(
      classifyPolicy([policyFile('AI disclosure is required.\nAI requires approval.')]).ai
    ).toBe('requires_approval');
    expect(
      classifyPolicy([
        policyFile('AI disclosure is required.\nAI requires approval.\nAI is banned.'),
      ]).ai
    ).toBe('banned');
    expect(classifyPolicy([policyFile('AI is not banned.')]).ai).toBe('banned');
    expect(classifyPolicy([policyFile('AI disclosure is required.\nAI is welcome.')]).ai).toBe(
      'unclear'
    );
  });
  it('retains commas in one unit but splits sentences, semicolons, newlines and list items', () => {
    expect(
      classifyPolicy([policyFile('It is not true, despite examples, that AI is welcome.')]).ai
    ).toBe('banned');
    for (const separator of ['.', '!', '?', ';', '\n- ', '\n* ', '\n+ ', '\n1. ', '\n2) ']) {
      expect(classifyPolicy([policyFile(`AI is banned${separator} AI is welcome`)]).ai).toBe(
        'unclear'
      );
    }
  });
  it('uses topic presence for boolean restrictions and never grants baseline permission', () => {
    expect(
      classifyPolicy([
        policyFile('Drafts are optional. Templates may be changed. Baseline failures are allowed.'),
      ])
    ).toMatchObject({
      draftRequired: true,
      receiptBlockAllowed: false,
      baselineFailuresPermitted: false,
    });
    expect(classifyPolicy([])).toMatchObject({
      ai: 'silent',
      assignment: 'unclear',
      directPr: 'unclear',
      draftRequired: false,
      receiptBlockAllowed: true,
      baselineFailuresPermitted: false,
    });
    expect(classifyPolicy([policyFile('No assignment is needed.')]).assignment).toBe('required');
    expect(classifyPolicy([policyFile('Discuss changes first before PRs.')]).directPr).toBe(
      'discussion_first'
    );
  });
  it('never returns permissive values across generated sentences and mixed policies', () => {
    const topics = [
      'AI',
      'A.I.',
      'LLM',
      'assistant',
      'Assignment',
      'Direct PRs',
      'Drafts',
      'Templates',
      'Baseline failures',
    ];
    const prefixes = ['', 'No ', 'Never ', 'It is not true, despite examples, that '];
    const suffixes = [
      ' are welcome.',
      ' are allowed, only after approval.',
      " aren't accepted.",
      ' require approval.',
      ' require disclosure.',
      ' are optional.',
      ' are not required.',
      ' are banned.',
      ' depend on judgment.',
    ];
    let checked = 0;
    for (const topic of topics)
      for (const prefix of prefixes)
        for (const suffix of suffixes) {
          const sentence = `${prefix}${topic}${suffix}`;
          for (const content of [
            sentence,
            `${sentence}\nAI is welcome.\nBaseline failures are allowed.`,
          ]) {
            const assessment = classifyPolicy([policyFile(content)]);
            expect(assessment.ai).not.toBe('welcomed');
            expect(assessment.directPr).not.toBe('welcomed');
            expect(assessment.assignment).not.toBe('not_required');
            expect(assessment.baselineFailuresPermitted).toBe(false);
            checked++;
          }
        }
    expect(checked).toBe(648);
  });
});

describe('retained evidence and digest guarantees', () => {
  it('cites scenario 1 at the original line and handles CRLF/case', () => {
    const assessment = classifyPolicy([
      policyFile('# Contributions\r\n\r\nLLM contributions are BANNED.'),
    ]);
    expect(assessment.ai).toBe('banned');
    expect(assessment.citations).toContainEqual({
      path: 'CONTRIBUTING.md',
      line: 3,
      ruleId: 'ai-ban-1',
      excerpt: 'LLM contributions are BANNED.',
    });
  });
  it('redacts entire secret-bearing lines even past the excerpt cap', () => {
    const secret = ['ghp', '_syntheticOnly'].join('');
    const a = classifyPolicy([policyFile(`AI is banned. ${'x'.repeat(220)} ${secret}`)]);
    expect(a.citations[0].excerpt).toBe('[redacted]');
    expect(JSON.stringify(a)).not.toContain(secret);
    expect(
      classifyPolicy([policyFile(`AI is banned. ${'x'.repeat(220)}`)]).citations[0].excerpt.length
    ).toBe(200);
  });
  it('binds sorted assessment keys/citations/path-SHA identities', () => {
    const files = [policyFile('AI is banned.'), policyFile('AI is welcome.', 'AI_POLICY.md')];
    const a = classifyPolicy(files);
    expect(classifyPolicy([...files].reverse())).toEqual(a);
    const digest = policyDigest(a, files);
    expect(digest).toMatch(/^[a-f0-9]{64}$/u);
    expect(
      policyDigest({ ...a, citations: [...a.citations].reverse() }, [...files].reverse())
    ).toBe(digest);
    expect(policyDigest({ ...a, draftRequired: true }, files)).not.toBe(digest);
    expect(policyDigest(a, [{ ...files[0], sha: 'a'.repeat(40) }, files[1]])).not.toBe(digest);
    expect(policyDigest(classifyPolicy([]), [])).toBe(
      '3236ec6be3056ffe44c3667e516c6bcb8c51fa9b5511f30e1839090e8fad581f'
    );
  });
  const filler =
    'AI is banned.\nAI requires approval.\nAI disclosure required.\nAssignment is required.\nNo assignment needed.\nPRs require approval.\nNo PRs.\nDraft required.\nNo drafts.\nKeep template unchanged.\nNo templates.\nNo baseline failures.';
  it('continues classification when the first nonrestrictive topic follows the evidence cap', () => {
    const files = Array.from({ length: 15 }, (_, n) =>
      policyFile(filler, `.github/PULL_REQUEST_TEMPLATE/${String(n).padStart(2, '0')}.md`)
    );
    files.push(policyFile('AI is welcome.', '.github/PULL_REQUEST_TEMPLATE/zzz.md'));
    const a = classifyPolicy(files);
    expect(a.citations).toHaveLength(128);
    expect(a.ai).toBe('unclear');
    expect(classifyPolicy([...files].reverse())).toEqual(a);
    expect(policyDigest(a, [...files].reverse())).toBe(policyDigest(a, files));
  });
  it('digests accepted worst-case escaped citation payloads without altering receipt limits', () => {
    const text = filler
      .split('\n')
      .map((line) => `${line} ${'\u0001'.repeat(200)}`)
      .join('\n');
    const files = Array.from({ length: 20 }, (_, n) =>
      policyFile(text, `.github/PULL_REQUEST_TEMPLATE/${n}.md`)
    );
    const a = classifyPolicy(files);
    expect(a.citations).toHaveLength(128);
    expect(policyDigest(a, files)).toMatch(/^[a-f0-9]{64}$/u);
    expect(() => canonicalJson('x', 0)).toThrow(ReceiptError);
    expect(() => canonicalJson('x', 1024 * 1024 + 1)).toThrow(ReceiptError);
  });
  it.each([
    [policyFile('safe', '../CONTRIBUTING.md')],
    [{ ...policyFile('safe'), sha: 'bad' }],
    [policyFile('\ud800')],
    [policyFile('x'.repeat(256 * 1024 + 1))],
    [policyFile('a'), policyFile('b')],
    Array.from({ length: 21 }, (_, n) => policyFile('', `.github/PULL_REQUEST_TEMPLATE/${n}.md`)),
    Array.from({ length: 5 }, (_, n) =>
      policyFile('x'.repeat(256 * 1024), `.github/PULL_REQUEST_TEMPLATE/${n}.md`)
    ),
  ])('rejects invalid direct snapshots %#', (...files) => {
    expect(() => classifyPolicy(files)).toThrow(PolicyInputError);
  });
  it('keeps hostile long-line scanning bounded', () => {
    const start = Date.now();
    expect(classifyPolicy([policyFile('a.'.repeat(100000))]).ai).toBe('silent');
    expect(Date.now() - start).toBeLessThan(5000);
  });
});
